apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  allowedRegistriesForImport:
    - domainName: quay.io
    - domainName: registry.redhat.io
    - domainName: registry.access.redhat.com
    - domainName: docker.io
